### ISSUE TITLE
publish to marketplace

### ISSUE THREAD

**Issue by ssbarnea** [flaregames/slack-for-confluence#1]
Is there any reason why this plugin is not published to the Atlassian marketplace?

**Comment by BenRomberg** [comment]
We've never done that before. Do you know how much effort that would be?

**Comment by ssbarnea** [comment]
Is easier than you may think. The only annoying part is that you need to upload 3 screenshots for the plugin. I could even help you with the process if you want.

**Comment by mbseid** [comment]
:+1: I would love this. We have been using rss and zapier and it is pretty meh. A native version would be awesome

**Comment by mathieumg** [comment]
:+1: +1 for this!

**Comment by BenRomberg** [comment]
Finally got around to do this, took around 1.5 hours taking proper screenshots, writing nice descriptions etc. :-)
Just submitted the add-on, waiting for approval from Atlassian.

**Comment by mathieumg** [comment]
Awesome, thanks! :tada:

Will be watching https://marketplace.atlassian.com/search?application=confluence&category=&cost=&hosting=&marketingLabel=&q=slack closely. :smiling_imp:

**Comment by BenRomberg** [comment]
"Your add-on has been reviewed and approved for distribution over the Atlassian Marketplace. Congratulations! If I can answer any other questions for you please let me know. Cheers!"

It's available on https://marketplace.atlassian.com/plugins/com.flaregames.slack-for-confluence

It seems that it's not available for cloud instances though. As far as I understand it, the addon would need to be completely rewritten and permanently hosted on a provided server using Atlassian Connect.

**Comment by mathieumg** [comment]
I installed it earlier today and it works well, thank you again! :+1:
