### ISSUE TITLE
Include diff of old/new page in notification

### ISSUE THREAD

**Issue by stilkov** [flaregames/slack-for-confluence#7]
It would be great if the diff of the old and new page of an edited page were included in the change message, similar to email notifications.

I understand this is a side project, I’m basically checking whether a PR would be accepted. As I don’t have Confluence API experience, a hint about how to do this would be appreciated as well – I’m not sure it’s easily possible at all.

**Comment by BenRomberg** [comment]
Hm, don't know if that's a good idea. Diffs can be quite large, you'd have to make some sort of sophisticated logic how to reduce it, and I don't know if Slack's capabilities to style the message are sufficient to effectively show a diff. See https://api.slack.com/docs/attachments for more info regarding styling possibilities in Slack messages.

**Comment by stilkov** [comment]
I agree, I played with the Confluence API a bit and don’t see an easy way to get at this at all, so I’m closing this.
