### ISSUE TITLE
Support for Cloud Confluence instances

### ISSUE THREAD

**Issue by ssbarnea** [flaregames/slack-for-confluence#9]
Support for Cloud Confluence instances, more and more instances are moving to the Cloud, remember that Slack is a cloud product.

It would be good to mention that Atlassian can give you a test instance for free. I got one at https://pycontribs.atlassian.net for testing integrations of JIRA Python library which is also open source.

If you want I can give you full access to it, I am not using the Confluence instance at all.

**Comment by BenRomberg** [comment]
Out of scope for this little project. Wouldn't even accept a PR, since it's probably best to start this as a completely new project since we wouldn't be able to maintain it.
